# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setup node with version 12.x and NPM registry url
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        registry-url: "https://registry.npmjs.org"
    # Run yarn install to install project packages
    - run: npm install
    # yarn build to build the project
    - run: npm build
    # publish the files to NPM
    - run: npm publish --access public
    # for publishing, npm need authorization. We add the NPM token to the environment which will take care of authorization to publish to the package
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
